use_frameworks!

target 'ReactiveNetwork_Example' do
  pod 'ReactiveNetwork', :path => '../'

  target 'ReactiveNetwork_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
